version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: DjangoTest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

  web:
    build:
      context: ./testdjango  # Указывает на поддиректорию с Dockerfile
      dockerfile: Dockerfile  # Указывает имя Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./testdjango:/app  # Указывает, что приложение находится в поддиректории
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
